# Generated by Django 4.2.26 on 2025-11-29 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskChunkingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_task_title', models.CharField(help_text='Title of the main task or assignment', max_length=255)),
                ('is_complete', models.BooleanField(default=False, help_text='Whether the overall task has been completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this task chunking was created')),
                ('user', models.ForeignKey(help_text='The user this task chunking belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='task_chunkings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_description', models.CharField(help_text='Description of the actionable step', max_length=255)),
                ('is_step_complete', models.BooleanField(default=False, help_text='Whether this step is complete')),
                ('order', models.IntegerField(help_text='Order of this step within the task chunk')),
                ('task_chunk', models.ForeignKey(help_text='The parent task chunk this step belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.taskchunkingmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PomodoroTimerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_duration', models.IntegerField(default=25, help_text='Work interval duration in minutes')),
                ('break_duration', models.IntegerField(default=5, help_text='Short break duration in minutes')),
                ('long_break_duration', models.IntegerField(default=15, help_text='Long break duration in minutes')),
                ('cycles_to_long_break', models.IntegerField(default=4, help_text='Number of work/break cycles before a long break')),
                ('current_status', models.CharField(help_text="Current timer status (e.g., 'Working', 'Breaking', 'Paused')", max_length=20)),
                ('session_start_time', models.DateTimeField(blank=True, help_text='When the current Pomodoro session started', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user this Pomodoro timer configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_timers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The message content')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the message was created')),
                ('recipient', models.ForeignKey(help_text='The user who received the message', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='The user who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['recipient', 'timestamp'], name='core_messag_recipie_f060c7_idx'), models.Index(fields=['sender', 'timestamp'], name='core_messag_sender__a9bcec_idx')],
            },
        ),
    ]
