# Generated by Django 5.2.8 on 2025-11-28 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short name/identifier for the AI persona (e.g., DANI, LUCAS)', max_length=50, unique=True)),
                ('full_name', models.CharField(help_text='Full name or acronym definition (e.g., "Discover, Adapt, Nurture & Inspire")', max_length=200)),
                ('system_prompt', models.TextField(help_text="System prompt that defines the AI persona's behavior and personality")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Persona',
                'verbose_name_plural': 'AI Personas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The message content')),
                ('is_from_bot', models.BooleanField(default=False, help_text='True if message is from the AI bot, False if from the user')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the message was created')),
                ('ai_persona', models.ForeignKey(help_text='The AI persona involved in this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='assistants.ai_persona')),
                ('user', models.ForeignKey(help_text='The user who sent or received this message', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['user', 'ai_persona', 'timestamp'], name='assistants__user_id_3deab0_idx')],
            },
        ),
    ]
