# Generated by Django 5.2.8 on 2025-11-28 15:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the adaptive rule (e.g., "Low Stimulus Trigger")', max_length=200, unique=True)),
                ('condition', models.TextField(help_text='Text description of the condition that triggers this rule')),
                ('action_payload', models.JSONField(default=dict, help_text='JSON payload defining what action to take when rule is triggered (e.g., {"mode": "dark"})')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EngagementMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_on_task', models.FloatField(default=0.0, help_text='Time spent on task in minutes', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('completion_rate', models.FloatField(default=0.0, help_text='Completion rate as a percentage (0.0 to 100.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('idle_ratio', models.FloatField(default=0.0, help_text='Ratio of idle time to active time (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this metric was recorded')),
                ('user', models.ForeignKey(help_text='The user whose engagement is being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='adaptive_en_user_id_e6021a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SensoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_score', models.FloatField(default=0.0, help_text='Mood score ranging from -1.0 (negative) to 1.0 (positive)', validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('sensory_overload_flag', models.BooleanField(default=False, help_text='True if user is experiencing sensory overload')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this log entry was created')),
                ('user', models.ForeignKey(help_text='The user whose sensory state is being logged', on_delete=django.db.models.deletion.CASCADE, related_name='sensory_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='adaptive_en_user_id_338df9_idx')],
            },
        ),
    ]
